// <auto-generated />
using System;
using CarDetails.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDetails.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231229024842_ThirdMigration")]
    partial class ThirdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("CarDetails.Models.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstInspection")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInspectionExpired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoadWorthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastInspection")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextInspection")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
