// <auto-generated />
using System;
using CarDetails.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDetails.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("CarDetails.Models.Cars", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstInspection")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInspectionExpired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoadWorthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastInspection")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextInspection")
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrationId");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
